# Name of the workflow as it appears in GitHub Actions UI
name: Job Offers API

# Define when this workflow will run
on:
  workflow_dispatch: # Allow manual triggering from GitHub UI
  push:
    branches:
      - main # Run automatically when code is pushed to main branch

# Environment variables used throughout the workflow
env:
  AZURE_WEBAPP_NAME: job-offers-api
  AZURE_WEBAPP_PACKAGE_PATH: src/Bootstrapper/JobOffersApi.Bootstrapper/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src/Bootstrapper/JobOffersApi.Bootstrapper
  SOLUTION_FILE: JobOffersApi.sln

# Define the separate jobs that make up this workflow
jobs:
  # First job: build and test the application
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest # Use Ubuntu runner for this job

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test Unit Users
        run: dotnet test src/Modules/Users/tests/JobOffersApi.Modules.Users.Tests.Unit/JobOffersApi.Modules.Users.Tests.Unit.csproj --no-restore --no-build --verbosity normal

      - name: Test Integration Users
        run: dotnet test src/Modules/Users/tests/JobOffersApi.Modules.Users.Tests.Integration/JobOffersApi.Modules.Users.Tests.Integration.csproj --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      # Store the published output as an artifact for later jobs
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp  # Name of the artifact
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # Second job: deploy the application to Azure
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test] # This job depends on the build-and-test job

    steps:
      # Retrieve the artifacts from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Deploy to Azure App Service using publish profile credentials
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          # Authentication credentials stored as a secret
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
